FROM ${IMAGE_PARENT}
LABEL maintainer ${MAINTAINER}

ADD rootfs.tar /
ADD goss.yaml /

#COPY docker-healthcheck.sh /usr/bin/docker-healthcheck
#HEALTHCHECK --interval=60s --timeout=5s --start-period=5s --retries=3 CMD ["docker-healthcheck"]

ENTRYPOINT [ "/goss" ]
#CMD ["/bin/some-cmd", "--some-option", "some-value"]
CMD [ "--help" ]
