# syntax=docker/dockerfile:1

# Global ARGS can be used in FROM lines, need to come before the first FROM.
ARG PORTAGE=gentoo/portage
ARG BASE_IMAGE=gentoo/stage3

FROM $PORTAGE AS portage

FROM $BASE_IMAGE
# This will create a layer
COPY --from=portage --link /var/db/repos /var/db/repos
