name: Agent
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: read

jobs:
  azure:
    name: Azure
    runs-on: ubuntu-latest
    steps:
      - name: 🐋 Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker pull agent
        run: |
          docker pull ghcr.io/berney/aether-tunnel/agent || echo "Failed to pull image"

      - name: Extract Agent
        run: |
          docker create --name agent ghcr.io/berney/aether-tunnel/agent
          pwd
          mkdir etc
          docker cp agent:/etc/s6_finish_default etc/
          docker cp agent:/etc/service/ etc/
          docker cp agent:/service/ .
          docker cp agent:/usr/bin/ .
          docker cp agent:/usr/local/bin/ .
          touch service/web-shell/down
          touch service/nginx/down
          export PATH="$(pwd)/bin:$PATH"
          s6-svscan service &

      - name: docker run agent
        if: false
        run: |
          docker run -d --name agent ghcr.io/berney/aether-tunnel/agent || echo "Failed to run image"

      - name: Inspect
        run: |
          sleep 10
          ps -ef
          pstree
          docker ps
          docker ps -a
          ss -nlt
          ss -nlu
          ip link
          ip addr
          ip -6 addr

      - name: Sleep
        run: |
          sleep 60m

      - name: Stop Agent
        if: false
        run: |
          docker stop agent
          docker rm agent
