name: Agent
on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main

permissions:
  contents: read
  packages: read

jobs:
  agent:
    name: Agent
    runs-on: ubuntu-latest
    steps:
      - name: 🐋 Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker pull agent
        run: |
          docker pull ghcr.io/berney/aether-tunnel/agent || echo "Failed to pull image"

      - name: Extract Agent
        env:
          LIGOLO_PROXY: ${{ secrets.LIGOLO_PROXY }}
        run: |
          docker create --name agent ghcr.io/berney/aether-tunnel/agent
          pwd
          mkdir etc
          docker cp agent:/etc/s6_finish_default etc/
          docker cp agent:/etc/service/ etc/
          docker cp agent:/service/ .
          docker cp agent:/usr/bin/ .
          docker cp agent:/usr/local/bin/ .
          docker rm agent
          touch service/web-shell/down
          touch service/nginx/down
          export PATH="$(pwd)/bin:$PATH"
          mkdir ~/log
          s6-svscan service &

      - name: docker run agent
        if: false
        run: |
          docker run -d --name agent ghcr.io/berney/aether-tunnel/agent || echo "Failed to run image"

      - name: Sleep
        run: |
          set -eux
          LOOPS=12
          for x in $(seq $LOOPS); do
            echo "== $x/$LOOPS"
            ps -ef
            pstree
            docker ps
            docker ps -a
            ss -nlt
            ss -nlu
            ip link
            ip addr
            ip -6 addr
            ls -l ~/log/mosh-server/current || true
            cat ~/log/mosh-server/current || true
            ls -l ~/log/ligolo-ng/current || true
            cat ~/log/ligolo-ng/current || true
            sleep 5m
          done

      - name: Stop Agent
        if: false
        run: |
          docker stop agent
          docker rm agent
