name: Azure
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  azure:
    name: Azure
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
      - name: Blob FUSE
        run: |
          set -eux
          sudo apt update
          sudo apt-get install -y blobfuse2
          ls -la /mnt
          cat /mnt/DATALOSS_WARNING_README.txt
          free -h || true
          free -m
          lsblk
          nproc
          mount
          cat /proc/mounts
          type blobfuse2 || true
          df -h /tmp
          curl -H "Metadata: true" "http://169.254.169.254/metadata/instance?api-version=2021-02-01" -s | jq .
          # Gets an OAUTH2 Access Token to the whole Storage Account
          # Alternatively could get a SAS to the storage container
          ACCESS_TOKEN=$(az account get-access-token --resource https://storage.azure.com/ --query accessToken --output tsv)
          cat <<-EOF > config.yaml
            logging:
              level: log_debug
              file-path: "blobfuse2-logs.txt"
              type: base
            azstorage:
              account-name: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
              container: ${{ secrets.AZURE_STORAGE_CONTAINER }}
              mode: azcli
          EOF
          #    account-key: ${ACCESS_TOKEN}
          cat config.yaml
          #auth_type: OAuth
          #oauth2_token: ${ACCESS_TOKEN}
          sudo mkdir -p /mnt/blobfuse2
          sudo mkdir -p /mnt/blobfuse2tmp
          sudo blobfuse2 mount /mnt/blobfuse2 --config-file=config.yaml --tmp-path=/mnt/blobfuse2tmp || ls -l blbofuse2-logs.txt && cat blobfuse2-logs.txt && false
          ls -la /mnt/blobfuse2
          echo "Hello World" > /mnt/blobfuse2/hello.txt
          cat /mnt/blobfuse2/hello.txt
