name: Kubler Cache Delete File(s)

on:
  workflow_dispatch:
    inputs:
      filespec:
        description: Filespec to use for removing files
        required: true
        default: downloads/portage-*.tar.*

jobs:
  kubler-cache-delete-files:
    runs-on: ubuntu-latest
    steps:
      - name: 🔎 Show Inputs
        run: |
          echo "Filespec is: ${{ inputs.filespec }}"

      # Cache Versions are based off key and path, so differnt path's can use same key
      #
      # Caches are immutable, so need unique key to create a new cache
      # `restore-keys` provides a list to restore a cache when key doesn't match
      # If there's no exact match, the most recent cache that partially matches will be used
      #
      - name: Cache Kubler Downloads
        uses: actions/cache@v3
        with:
          path: ~/.kubler/downloads/
          key: kubler-${{ github.sha }}
          restore-keys: |
            kubler-

      - name: Cache Kubler Gentoo Distfiles
        uses: actions/cache@v3
        with:
          path: ~/.kubler/distfiles/
          key: kubler-${{ github.sha }}
          restore-keys: |
            kubler-

      - name: Cache Kubler Gentoo Packages
        uses: actions/cache@v3
        with:
          path: ~/.kubler/packages/
          key: kubler-${{ github.sha }}
          restore-keys: |
            kubler-

      - name: Inspect Kubler Caches
        run: |
          tree -a -C ~/.kubler

      - name: 🔎 List Files
        run: |
          ls -l ~/.kubler/${{ inputs.filespec }}

      - name: 🔥 Remove File
        run: |
          rm -rf ~/.kubler/${{ inputs.filespec }}

      - name: Inspect Kubler Caches Again
        run: |
          tree -a -C ~/.kubler

