name: Chain Builders-Kubler
on:
  workflow_dispatch:
    inputs:
      portage_date:
        description: The date (tag) of the latest portage image (e.g. `20241231`)
        default: latest
      portage_image:
        description: Portage Image (e.g. `ghcr.io/berney/kubler-images/portage:20241231`)
        required: true
        type: string

jobs:
  call-builders:
    uses: ./.github/workflows/builders.yml
    with:
      portage_date: ${{ inputs.portage_date }}
      portage_image: ${{ inputs.portage_image }}
  call-kubler-build:
    uses: ./.github/workflows/kubler-build.yml
    needs: call-builders
    with:
      portage_date: ${{ inputs.portage_date }}
      portage_image: ${{ inputs.portage_image }}
